### ISSUE TITLE
Markierungen: Letzte Markierungen Text tauschen

### ISSUE THREAD

**Issue by avoelker-letsdev** [letsdev/dico-scanner-app-ios#3]
Text rot unter "Meine letzten Markierungen", wenn in der Liste ein Eintrag steht, sollte hier die Dauer bis zum letzten Tracking stehen, ansonsten "Es wurde noch keine Markierung gesetzt"

**Comment by sebastian-ruf** [comment]
Ist gefixt auf dem develop
