### ISSUE TITLE
Symptome: SARS-CoV-2 Testergebnisse

### ISSUE THREAD

**Issue by avoelker-letsdev** [letsdev/dico-scanner-app-ios#4]
Unter der Überschrift mit dem Button gibt es dann (sofern man Tests dokumentiert hat) eine Liste der Ergebnisse. => Ansonsten steht nur die Überschrift mit dem Plus Button

Überschrift ist immer SARS-CoV-2 Test vom xx.xx.xxxx (Datum) und darunter das Ergebnis (positiv/negativ/ausstehend)

**Comment by fabiankoebel** [comment]
Das Datum wird jetzt schon mal gesetzt
