### ISSUE TITLE
SymptomGetRequest legt Symptome immer neu an

### ISSUE THREAD

**Issue by fabiankoebel** [letsdev/dico-scanner-app-ios#8]
bei jedem Abruf wird die Symptomliste erneut als Duplikate in der DB angelegt

**Comment by sebastian-ruf** [comment]
Das liegt am Predicate beim UUID Abruf. Am Call selbst hab ich noch angepasst, warum er das Predicate nicht nimmt hab ich nicht rausgefunden.
